version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node@2.0.2
    steps:
      - checkout
      - run:
          command: apt install gmp-dev -y
      - run:
          command: npm install
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          command: npm install
      - run:
          command: npm test
workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.14.0
      - node/test:
          version: 12.18.2
      - node/test:
          version: 11.15.0
      - node/test:
          version: 10.21.0
